wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.15
    code_path: code/EVERGI/sweep_tune_GEP.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.5
    t:
      1:
      - 3
      - 5
      4: 3.7.5
      5: 0.10.15
batchsize:
  desc: null
  value: 2000
cell_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.2
layers:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.1
