wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.20
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.6
    session_history: code/_session_history.ipynb
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      - 3
      4: 3.8.6
      5: 0.10.20
      8:
      - 1
      - 5
architecture:
  desc: null
  value: RNN with forward lags for temporal
batch_size:
  desc: null
  value: 1500
dataset:
  desc: null
  value: Columbia
epochs:
  desc: null
  value: 12
patience:
  desc: null
  value: 10
